[tool.poetry]
name = "shelf"
version = "0.1.0"
description = ""
authors = ["Slava <brainout8@gmail.com>"]
readme = "README.md"

[tool.poe.tasks]

# =========================
# Database migrations
# =========================

makemigrations = "docker exec ${PROJECT_NAME}_api alembic revision --autogenerate -m 'new revision'"

migrate = "docker exec ${PROJECT_NAME}_api alembic upgrade head"

downgrade = "docker exec ${PROJECT_NAME}_api alembic downgrade base"


# =========================
# Ruff linting
# =========================

lint = "ruff check ."

lint-fix = "ruff check . --fix"

format = "ruff format ."

format-check = "ruff format . --check"


[tool.poetry.dependencies]
python = "3.12.*"
psycopg2-binary = "2.9.9"
fastapi = "^0.115.12"
uvicorn = "^0.34.2"
sqlalchemy = "^2.0.41"
asyncpg = "^0.30.0"
pydantic = "^2.11.5"
alembic = "^1.16.1"
python-dotenv = "^1.1.0"
httpx = "^0.28.1"
pydantic-settings = "^2.13.1"
python-jose = { extras = ["cryptography"], version = "^3.5.0" }


[tool.poetry.group.dev.dependencies]
poethepoet = "^0.34.0"
ruff = "^0.4.0"
alembic = "^1.16.4"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"
pytest-asyncio = "^0.26.0"


[tool.ruff]
line-length = 120


[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    "W",

    # Pyflakes
    "F",

    # mccabe
    "C901",

    # flake8-bugbear
    "B",

    # flake8-print
    "T20",

    # flake8-mutable
    "B006",

    # flake8-builtins
    "A",

    # flake8-pydocstyle
    "D",

    # flake8-async
    "ASYNC",

    # pep8-naming
    "N",

    # tryceratops
    "TRY",

    # flake8-bandit
    "S",
]

ignore = [
  "D203",  # Conflicts with D211
  "D213",  # Conflicts with D212
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "D100",  # Test module names describe their purpose.
    "D103",  # Test function names describe their behavior.
    "D104",  # Test package marker files do not need docstrings.
    "S101",  # Pytest uses assert statements for checks.
]


[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true


[tool.ruff.lint.pep8-naming]
classmethod-decorators = [
    "classmethod",
    "classproperty",
]


[tool.pytest.ini_options]
pythonpath = "src"
