"""New revision.

Revision ID: 30ff8478a483
Create Date: 2026-04-05 21:15:11.481204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ff8478a483'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_works',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('year_composed', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('style', sa.String(length=100), nullable=False),
    sa.Column('tracks', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_works_artist'), 'album_works', ['artist'], unique=False)
    op.create_index(op.f('ix_album_works_created_by'), 'album_works', ['created_by'], unique=False)
    op.create_index(op.f('ix_album_works_genre'), 'album_works', ['genre'], unique=False)
    op.create_index(op.f('ix_album_works_is_public'), 'album_works', ['is_public'], unique=False)
    op.create_index(op.f('ix_album_works_is_verified'), 'album_works', ['is_verified'], unique=False)
    op.create_index(op.f('ix_album_works_style'), 'album_works', ['style'], unique=False)
    op.create_index(op.f('ix_album_works_title'), 'album_works', ['title'], unique=False)
    op.create_index(op.f('ix_album_works_updated_by'), 'album_works', ['updated_by'], unique=False)
    op.create_index(op.f('ix_album_works_year_composed'), 'album_works', ['year_composed'], unique=False)
    op.create_table('storage_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('album_work_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('tracklist', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_work_id'], ['album_works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_created_by'), 'releases', ['created_by'], unique=False)
    op.create_index(op.f('ix_releases_is_public'), 'releases', ['is_public'], unique=False)
    op.create_index(op.f('ix_releases_is_verified'), 'releases', ['is_verified'], unique=False)
    op.create_index(op.f('ix_releases_label'), 'releases', ['label'], unique=False)
    op.create_index(op.f('ix_releases_updated_by'), 'releases', ['updated_by'], unique=False)
    op.create_index(op.f('ix_releases_year'), 'releases', ['year'], unique=False)
    op.create_table('storage_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('storage_type', sa.Enum('SHELF', 'FRAME', 'STAND', 'BOX', name='storage_type'), nullable=False),
    sa.Column('form_vector', sa.JSON(), nullable=False),
    sa.Column('position_vector', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['storage_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.Enum('VINYL', 'CD', 'CASSETTE', name='medium_format'), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('sides', sa.JSON(), nullable=False),
    sa.Column('color_hint', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediums_created_by'), 'mediums', ['created_by'], unique=False)
    op.create_index(op.f('ix_mediums_format'), 'mediums', ['format'], unique=False)
    op.create_index(op.f('ix_mediums_is_public'), 'mediums', ['is_public'], unique=False)
    op.create_index(op.f('ix_mediums_is_verified'), 'mediums', ['is_verified'], unique=False)
    op.create_index(op.f('ix_mediums_updated_by'), 'mediums', ['updated_by'], unique=False)
    op.create_table('user_albums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('medium_id', sa.UUID(), nullable=False),
    sa.Column('custom_notes', sa.String(length=500), nullable=True),
    sa.Column('custom_cover', sa.String(), nullable=True),
    sa.Column('vinyl_grade', sa.Enum('M', 'NM', 'VG_PLUS', 'VG', 'G_PLUS', 'G', 'F', 'P', name='vinyl_grade'),
              nullable=True),
    sa.Column('sleeve_grade', sa.Enum('SS', 'M', 'NM', 'VG_PLUS', 'VG', 'G_PLUS', 'G', 'F', 'P', name='sleeve_grade'),
              nullable=True),
    sa.Column('is_shared', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medium_id'], ['mediums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('storage_item_id', sa.UUID(), nullable=False),
    sa.Column('user_album_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['storage_item_id'], ['storage_items.id'], ),
    sa.ForeignKeyConstraint(['user_album_id'], ['user_albums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_album_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_slots')
    op.drop_table('user_albums')
    op.drop_index(op.f('ix_mediums_updated_by'), table_name='mediums')
    op.drop_index(op.f('ix_mediums_is_verified'), table_name='mediums')
    op.drop_index(op.f('ix_mediums_is_public'), table_name='mediums')
    op.drop_index(op.f('ix_mediums_format'), table_name='mediums')
    op.drop_index(op.f('ix_mediums_created_by'), table_name='mediums')
    op.drop_table('mediums')
    op.drop_table('storage_items')
    op.drop_index(op.f('ix_releases_year'), table_name='releases')
    op.drop_index(op.f('ix_releases_updated_by'), table_name='releases')
    op.drop_index(op.f('ix_releases_label'), table_name='releases')
    op.drop_index(op.f('ix_releases_is_verified'), table_name='releases')
    op.drop_index(op.f('ix_releases_is_public'), table_name='releases')
    op.drop_index(op.f('ix_releases_created_by'), table_name='releases')
    op.drop_table('releases')
    op.drop_table('storage_groups')
    op.drop_index(op.f('ix_album_works_year_composed'), table_name='album_works')
    op.drop_index(op.f('ix_album_works_updated_by'), table_name='album_works')
    op.drop_index(op.f('ix_album_works_title'), table_name='album_works')
    op.drop_index(op.f('ix_album_works_style'), table_name='album_works')
    op.drop_index(op.f('ix_album_works_is_verified'), table_name='album_works')
    op.drop_index(op.f('ix_album_works_is_public'), table_name='album_works')
    op.drop_index(op.f('ix_album_works_genre'), table_name='album_works')
    op.drop_index(op.f('ix_album_works_created_by'), table_name='album_works')
    op.drop_index(op.f('ix_album_works_artist'), table_name='album_works')
    op.drop_table('album_works')
    # ### end Alembic commands ###
